import img1 from "../../assets/images/img1.png"
export const data = [
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
  {
    companyName: "Digital Creative",
    product:
      "Product (UI/UX) Design: Designing solution that help people live a better life",
    price: "#3,000",
    duration: "3 months",
    noOftasks: "10 tasks",
    img: img1,
    skills: [
      "Product thinking",
      "UI Design",
      "Adobe XD",
      "Sketch",
      "Figma",
      "Critical thinking",
      "Problem solving",
      "Time management",
    ],
  },
];


export const cards = [
  {
    fullName: "John Doe",
    message : "Fantastic digital marketing internship! Supportive team, hands-on learning, and valuable insights into diverse strategies. Contributed meaningfully to projects, strategies. Contributed meaningfully to projects, strategies.",
    profileImg: "",
  },
  {
    fullName: "John Doe",
    message : "Fantastic digital marketing internship! Supportive team, hands-on learning, and valuable insights into diverse strategies. Contributed meaningfully to projects, strategies. Contributed meaningfully to projects, strategies.",
    profileImg: "",
  },
  {
    fullName: "John Doe",
    message : "Fantastic digital marketing internship! Supportive team, hands-on learning, and valuable insights into diverse strategies. Contributed meaningfully to projects, strategies. Contributed meaningfully to projects, strategies.",
    profileImg: "",
  },
  {
    fullName: "John Doe",
    message : "Fantastic digital marketing internship! Supportive team, hands-on learning, and valuable insights into diverse strategies. Contributed meaningfully to projects, strategies. Contributed meaningfully to projects, strategies.",
    profileImg: "",
  },
  {
    fullName: "John Doe",
    message : "Fantastic digital marketing internship! Supportive team, hands-on learning, and valuable insights into diverse strategies. Contributed meaningfully to projects, strategies. Contributed meaningfully to projects, strategies.",
    profileImg: "",
  },
]