export const skills = [
  "HTML",
  "CSS",
  "JavaScript",
  "React",
  "Node",
  "Express",
  "MongoDB",
  "Python",
  "Django",
  "Flask",
  "PostgreSQL",
  "MySQL",
  "Firebase",
  "AWS",
  "Azure",
  "GCP",
  "Docker",
  "Kubernetes",
  "Jenkins",
  "Git",
  "CI/CD",
  "Linux",
  "Windows",
  "MacOS",
  "Android",
  "iOS",
  "Flutter",
  "React Native",
  "Swift",
  "Kotlin",
  "Java",
  "C#",
  "C++",
  "Ruby",
  "Go",
  "Rust",
  "Scala",
  "Haskell",
  "TypeScript",
  "GraphQL",
  "REST",
  "API",
  "Microservices",
  "Serverless",
  "Blockchain",
  "Machine Learning",
  "Deep Learning",
  "Data Science",
  "Big Data",
  "Data Engineering",
  "Data Analysis",
  "Data Visualization",
  "Business Intelligence",
  "ETL",
  "Data Warehousing",
  "Data Mining",
  "Data Modeling",
  "Data Governance",
  "Data Quality",
  "Data Security",
  "Data Privacy",
  "Data Ethics",
  "Data Compliance",
  "Data Strategy",
  "Data Management",
  "Data Integration",
  "Data Migration",
  "Data Architecture",
  "Data Lake",
  "Data Warehouse",
  "Data Mart",
  "Data Catalog",
  "Data Dictionary",
  "Data Lineage",
  "Data Profiling",
  "Data Cleansing",
  "Data Enrichment",
  "Data Normalization",
  "Data Aggregation",
  "Data Federation",
  "Web Development",
  "Mobile Development",
  "Desktop Development",
  "Cloud Development",
  "DevOps",
  "SRE",
  "Cybersecurity",
  "Information Security",
  "Network Security",
  "Cloud Security",
  "Application Security",
  "Security Operations",
  "Security Engineering",
  "Security Architecture",
  "software development",
  "software engineering",
  "software architecture",
  "software design",
  "software testing",
  "UI/UX",
  "Product Management",
  "figma",
  "adobe xd",
  "sketch",
  "invision",
  "zeplin",
  "prototyping",
  "wireframing",
  "mockups",
  "design systems",
  "design thinking",
  "user research",
  "usability testing",
  "interaction design",
  "visual design",
  "graphic design",
  "web design",
  "mobile design",
  "responsive design",
  "design principles",
  "typography",
  "color theory",
  "branding",
  "logo design",
  "illustration",
  "iconography",
  "motion design",
  "animation",
  "video editing",
  "audio editing",
  "photography",
  "videography",
  "3D modeling",
  "3D animation",
  "3D rendering",
  "3D printing",
  "augmented reality",
  "virtual reality",
];
