export const ActionTypes = {
    SET_USERNAME : "SET_USERNAME",
    SET_FULLNAME: "SET_FULLNAME",
    SET_EMAIL: "SET_EMAIL",
    SET_TOKEN: "SET_TOKEN",
    SET_SIGNIN_LOADING: "SET_SIGNIN_LOADING",
    SET_SIGNIN_ERROR: "SET_SIGNIN_ERROR",
    SET_SIGNUP_LOADING: "SET_SIGNUP_LOADING",
    SET_SIGNUP_ERROR: "SET_SIGNUP_ERROR",
    RESET: "RESET"
}