export const ActionTypes = {
  SET_USER: "SET_USER",
  SET_TOKEN: "SET_TOKEN",
  SET_SIGNIN_LOADING: "SET_SIGNIN_LOADING",
  SET_SIGNIN_ERROR: "SET_SIGNIN_ERROR",
  SET_SIGNUP_LOADING: "SET_SIGNUP_LOADING",
  SET_SIGNUP_ERROR: "SET_SIGNUP_ERROR",
  RESET: "RESET",
  IS_AUTH: "IS_AUTH",
  USERNAME_CHECK: "USERNAME_CHECK",
};
